### ISSUE TITLE
SpinNumCtrl minValue error when adding Trigger Event action

### ISSUE THREAD

**Issue by per1234** [EventGhost/EventGhost#191]
EventGhost version: build [397](https://ci.appveyor.com/api/buildjobs/m5n114engpecy9jk/artifacts/_build%2Foutput%2FEventGhost_WIP-2017.01.31-05.46.11_Setup.exe), [398](https://ci.appveyor.com/api/buildjobs/rp5f7983k4a9acdl/artifacts/_build%2Foutput%2FEventGhost_WIP-2017.01.31-16.30.01_Setup.exe), [408](https://ci.appveyor.com/api/buildjobs/9ocm8nip66yn75mu/artifacts/_build%2Foutput%2FEventGhost_0.5.0-beta6_Setup.exe)
OS: Windows 7 64 bit

Steps to reproduce:
1. Install build 397 or newer
2. Add Action > EventGhost > Trigger Event > OK

The Trigger Event action is not added and a traceback occurs:
```
14:29:54   Traceback (most recent call last) (0.5.0-beta6):
14:29:54     File "C:\Program Files (x86)\EventGhost\eg\Classes\TaskletDialog.py", line 162, in ProcessingTask
14:29:54       self.Configure(*args, **kwargs)
14:29:54     File "C:\Program Files (x86)\EventGhost\eg\Classes\ConfigDialog.py", line 106, in Configure
14:29:54       treeItem.Configure(*args)
14:29:54     File "C:\Program Files (x86)\EventGhost\eg\Classes\ActionItem.py", line 80, in Configure
14:29:54       return self.executable.Configure(*args)
14:29:54     File "C:\Program Files (x86)\EventGhost\plugins\EventGhost\__init__.py", line 624, in Configure
14:29:54       waitTimeCtrl = panel.SpinNumCtrl(waitTime, integerWidth=5)
14:29:54     File "C:\Program Files (x86)\EventGhost\eg\Classes\ControlProviderMixin.py", line 119, in SpinNumCtrl
14:29:54       return eg.SpinNumCtrl(self, -1, value, *args, **kwargs)
14:29:54     File "C:\Program Files (x86)\EventGhost\eg\Classes\SpinNumCtrl.py", line 90, in __init__
14:29:54       numCtrl.SetMin(minValue)
14:29:54   NameError: global name 'minValue' is not defined
14:29:54   Traceback (most recent call last) (0.5.0-beta6):
14:29:54     File "wx\_core.pyc", line 16766, in <lambda>
14:29:54     File "C:\Program Files (x86)\EventGhost\eg\Core.py", line 216, in Notify
14:29:54       listener(value)
14:29:54     File "C:\Program Files (x86)\EventGhost\eg\Classes\MainFrame\TreeCtrl.py", line 801, in OnNodeSelected
14:29:54       path = node.GetPath()
14:29:54     File "C:\Program Files (x86)\EventGhost\eg\Classes\TreeItem.py", line 282, in GetPath
14:29:54       path.append(parent.childs.index(item))
14:29:54   AttributeError: 'NoneType' object has no attribute 'childs'
```
This issue does not occur with build 393 or earlier, leading me to believe it was caused by https://github.com/EventGhost/EventGhost/pull/188

CC: @kdschlosser

**Comment by kdschlosser** [comment]
yup we know. and it has been fixed... :smile:

**Comment by kdschlosser** [comment]
I wanted to leave a note in here.. This issue has been fixed but because of some kind of an issue with the build system we can't get a build done. so if you remove line 98 from the file eg/Classes/SpinNumCtrl.py it will fix the problem. Cheers

ref PR #192

**Comment by per1234** [comment]
Fixed by https://github.com/EventGhost/EventGhost/commit/55c77bf7c10c2b7d9f4dec5535235990d784f75c
Thanks @kdschlosser!

**Comment by kdschlosser** [comment]
Werd.. would have been a few days ago. I have to check with topic to see what was going on with appveyor. And that was my screw up with this thing. I should have gotten it right the first time. Sorry for the inconvience

**Comment by per1234** [comment]
It was fixed in your PR a few days ago but we should only close issues after the PR is merged, which only happened 10 hours ago. You can actually cause GitHub to do this automatically by the use of certain keywords in the commit message:
https://help.github.com/articles/closing-issues-via-commit-messages/

**Comment by kdschlosser** [comment]
I know. it's fixed. I am just saying thank you for pointing out my mistake.. :smile: don't know what i would do without ya buddy
